### ISSUE TITLE
Support for Homebrew nvim?

### ISSUE THREAD

**Issue by kropper** [vv-vim/vv#1]
I have installed nvim via Homebrew. When trying to run VV.app, it tells me that neovim is not installed and offers to open the installation instructions. 

Is there any way to make it work with nvim installed via Homebrew?

**Comment by igorgladkoborodov** [comment]
Yes, that's a bug when you run it not from terminal, I've just noticed it too. Fixing it ASAP. You can build it manually and it will work. Or you can just run in terminal:
```
ln -s -f /Applications/VV.app/Contents/Resources/bin/vv /usr/local/bin/vv
```
And then just start it with `vv` command.

**Comment by kropper** [comment]
Thank you, that got me one step further. Running ``vv`` starts VV.app, and I don't get the error message as when running VV.app from Finder. However, VV.app apparently just locks up. I never get to see any application window, and via the Dock, VV.app can only be "force quit". Is there a way to diagnose why it does not start up properly?

**Comment by igorgladkoborodov** [comment]
Does it work with `vv -u NONE`?
If you just run `nvim` does it have any errors?
Can you also try to run `nvim --cmd "/Applications/VV.app/Contents/Resources/bin/vv.vim"` and see, does it have errors or not.

I am going to make some debug mode shortly to log errors.

**Comment by igorgladkoborodov** [comment]
https://github.com/igorgladkoborodov/vv/commit/e719dd8a92a129d331b15357f76667d68ef0aeff

**Comment by kropper** [comment]
Starting with ```-u NONE``` does not change anything: VV.app starts, but never shows a window and just can be force-quit.

**Comment by igorgladkoborodov** [comment]
Please try to update to the [new version](https://github.com/igorgladkoborodov/vv/releases/tag/v1.1.0) and run it with `vv --debug`. It will output errors to terminal. It only works with Neovim 0.3, that was released just yesterday. So please update it with `brew upgrade neovim`.
Thank you for helping me to debug it, hope this time it will work.

**Comment by kropper** [comment]
With nvim 0.3.0:

```
$ nvim --version
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
Übersetzt von brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/usr/local/Cellar/neovim/0.3.0/share/nvim"

Run :checkhealth for more info
```

and the 1.1 release of VV,

running 

```$ /Applications/VV.app/Contents/Resources/bin/vv -u NONE```

hangs as before. The VV.app icon shows up in the text. There is no application window, and with the dock icon, the application can just be force-quit.

Running ```nvim --cmd "/Applications/VV.app/Contents/Resources/bin/vv.vim"``` gives the error ```E486: Pattern not found: Applications```

**Comment by igorgladkoborodov** [comment]
Sorry, this is the correct command:
```
nvim --cmd "source /Applications/VV.app/Contents/Resources/bin/vv.vim"
```

And also could you please run:
```
/Applications/VV.app/Contents/Resources/bin/vv --debug
```

And this one:
```
node -e "const { spawn } = require('child_process'); spawn('nvim', [], { stdio: 'inherit' });"
```

Does any of these show you any error?

And btw, if you run it from Finder, does it show that popup that Neovim is not installed?

**Comment by kropper** [comment]
Running ```nvim --cmd "source /Applications/VV.app/Contents/Resources/bin/vv.vim"``` did not yield any error except a warning that a ```.swp``` file already exists.

Interestingly enough, starting with the ```--debug``` parameter made VV start up for me, showing an application window with netrw running.

More interestingly, since this first start in debug mode, I can run VV from the Finder in /Applications, and it starts up just fine.

So I'm certainly happy with that now, but don't know what the one-time start in debug mode changed to make it work now.

Anyway, thanks for your help, and this really does look promising, I'm looking forward to the next steps VV takes. :-)

**Comment by igorgladkoborodov** [comment]
Cool! Thank you for testing and for the first bug.

**Comment by ydzhou** [comment]
I am still having the same issue with vv cannot detect homebred-installed neovim if I start it from Finder in /Applications. Any thoughts? It works if I start it in terminal. I am using the binary release of 1.5.0.

**Comment by igorgladkoborodov** [comment]
@ydzhou Hm, can't reproduce. Do you use bash or other shell? What `which nvim` returns for you?
Can you also try this version https://github.com/vv-vim/vv/releases/tag/v1.2.0? I've made some changes that might be possibly related to this.

**Comment by ydzhou** [comment]
I am using zsh. 
which nvim returns /usr/local/bin/nvim (my nvim is installed via homebrew)

After switching to version 1.2.0, I do not have this issue anymore. But version 1.5.0 I still have the issue and I think that is the latest one. Kinda weird.

**Comment by igorgladkoborodov** [comment]
Looks like that's because you use zsh and it is trying to execute nvim via bash and you don't have /usr/local/bin in bash PATH. Will make a fix tomorrow.
Meanwhile I think it will work if you add ~/.bashrc file and add `export PATH=/usr/local/bin:$PATH` there.

**Comment by igorgladkoborodov** [comment]
@ydzhou Can you try this one? https://github.com/vv-vim/vv/releases/tag/v1.5.1

**Comment by ydzhou** [comment]
Well it is fixed! But when I click open in the menubar and select cancel in the dialog, it throws exception 

Uncaught Exception:
TypeError: Cannot read property 'length' of undefined
    at O.o.dialog.showOpenDialog.e (/Applications/VV.app/Contents/Resources/app.asar/build/main.js:1:3805)
    at Function.wrappedCallback (/Applications/VV.app/Contents/Resources/electron.asar/browser/api/dialog.js:130:57)

**Comment by ydzhou** [comment]
And I cannot close the app unless force-quitting...

**Comment by igorgladkoborodov** [comment]
Thank you for the new bug. Added as a separate issue #16
