### ISSUE TITLE
Set `gui_running`

### ISSUE THREAD

**Issue by lourenci** [vv-vim/vv#100]
Is there some way to set `gui_running`? A lot of plugins depend on it.

Thanks

**Comment by igorgladkoborodov** [comment]
Hi @lourenci

Neovim [stopped supporting](https://github.com/neovim/neovim/issues/5220) `gui_running` flag and I can't enable it from the client.

You can use different ways to detect GUI. For example, using [`UIEnter`](https://neovim.io/doc/user/autocmd.html#UIEnter) autocommand. Or if you want to have some VV-specific config, you can check `g:vv` variable for this. For third-party plugins that are using `gui_running`, I guess the only way to make them work is fork and fix them.
