### ISSUE TITLE
Infinite redraw events `win_viewport` in VISUAL mode with nvim v0.5.0

### ISSUE THREAD

**Issue by brookhong** [vv-vim/vv#117]
When running with nvim v0.5.0, the CPU load becomes very high if VISUAL mode was turned on. After adding log into the code, I found that infinite redraw events `win_viewport` were received, such as

    [ 2, 'redraw', [ [ 'win_viewport', [Array] ], [ 'flush', [] ] ] ]

Here is the command to start with nvim v0.5.0

    VV_NVIM_COMMAND="<path_to_nvim_v0.5.0>" yarn start:electron

**Comment by igorgladkoborodov** [comment]
@brookhong thank you. Looking at it.

**Comment by igorgladkoborodov** [comment]
@brookhong Fixed it, thank you for debugging

**Comment by brookhong** [comment]
@igorgladkoborodov Thanks for the fix, but it does not fix the problem completely. Another way to trigger the problem is to follow below steps:

1. install plugin `scrooloose/nerdtree`
2. open the NERDTree with command `NERDTree`

You can still see infinite redraw event `win_viewport` received. And from your comments just above current fix, `win_viewport` seems to be the new API that you need for cursor position, thus we might have to handle these `win_viewport` events.

**Comment by igorgladkoborodov** [comment]
@brookhong fixed it here #119.
We can't use `win_viewport` because it shows cursor position relative to the window, and we don't know it unless `ext_multigrid` is turned on.
I fixed it by moving the cursor position workaround to the `grid_cursor_goto` event. It seems to work fine now, both for Visual mode and with NERDTree.

**Comment by brookhong** [comment]
Thanks @igorgladkoborodov.

This seems to fix the problem, and why don't turn on`ext_multigrid`?

**Comment by igorgladkoborodov** [comment]
Merged it, thank you for help.

It will require a lot of work to rewrite rendering to `ext_multigrid` API, it will not work out out of the box. I want to experiment with this a little later. With `ext_multigrid` we can have some nice features like different font size for different windows.
