### ISSUE TITLE
Cannot configure fontfamily and fontsize for vv?

### ISSUE THREAD

**Issue by linrongbin16** [vv-vim/vv#127]
Hi, my vv cannot configure fontfamily and fontsize.

I want to set font to [Hack Nerd Font Mono](https://github.com/ryanoasis/nerd-fonts).

But it didn't work. Here's my vimrc setting:
```
if exists('g:vv')
  VVset fontfamily=Hack\ Nerd\ Font\ Mono
  VVset fontsize=12
endif
```

**Comment by igorgladkoborodov** [comment]
Hi @linrongbin16. Can you try to use the postscript name of the font like this: https://github.com/vv-vim/vv/issues/92#issuecomment-812129298
