### ISSUE TITLE
Text [Dead] on type Tilde, Accute, back accute, Caret, etc

### ISSUE THREAD

**Issue by artero** [vv-vim/vv#19]
On pressing the keys to write the symbols `^`  `~`  `´` `¨` appears the word `Dead` 😧. 

I'm using a Spanish keyboard on Mac OSX and the error happens with the Spanish and English layout.

**Comment by igorgladkoborodov** [comment]
Wow, that's spooky! I was able to reproduce it, will fix it later today.

**Comment by igorgladkoborodov** [comment]
Fixed. You can check updated version here: https://github.com/vv-vim/vv/releases/tag/v1.7.2
