### ISSUE TITLE
request: quit on close last window

### ISSUE THREAD

**Issue by davidosomething** [vv-vim/vv#25]

**Comment by justinmk** [comment]
How are you closing the window? `<c-w>c` and `:close` disallow this normally.

**Comment by davidosomething** [comment]
I mean quit vv.app when the last vv.app electron window closes, not the Vim "window" to a buffer

**Comment by igorgladkoborodov** [comment]
I followed the common pattern for Mac apps, when it keep running even if last window is closed. Also new windows will open much faster if it keep running (~2.5s vs <1s on my computer). You can Cmd+Q to quit app completely.

But I can add this customisable option.

**Comment by igorgladkoborodov** [comment]
This actually makes sense, when you do `:q`, you actually _mean_ to quit.

**Comment by justinmk** [comment]
What if multiple Nvim/VV instances are running? The way you've done it is correct for macOS. Users should be quite accustomed to cmd+q.

**Comment by igorgladkoborodov** [comment]
Quit if that was the last instance, and keep running if there are more instances.
