### ISSUE TITLE
CLI option to open files in existing window?

### ISSUE THREAD

**Issue by ronen** [vv-vim/vv#36]
Feature request:  An option to the CLI `vv` command that would request it to use an existing `vv` window and open the files in it (passing its remaining options to the existing `nvim` instance) rather than creating a new window & `nvim` instance.

I.e. similar behavior to MacVim's `gvim --remote` family of options.

That's a feature I use frequently and is what's holding me back from attempting to migrate from MacVim to to Neovim

Thanks!

**Comment by igorgladkoborodov** [comment]
Hi Ronen,

That’s an interesting feature request. What is your use case for this?

I am going to do something similar. I want to add an option to open files by default in the existing VV instance if that file is in the already opened project (i.e. the file to open is in subdirectory of `:pwd` of existing VV instance).

In my personal common workflow it will help opening files from terminal output, for example for failed tests.

Is your use case also project-oriented? Or you want to have a single VV instance and open files from different places to edit?

There is also a big question how exactly to open the file: in the existing window, in a new tab or split. Maybe it could be controlled by cli options similar to gvim's `--remote` or respect `switchbuf` setting or add specific VV settings or cli options. I don’t want to use `--remote*` CLI options from gvim to avoid confusion, because most likely it will have different functionality.

**Comment by ronen** [comment]
Hi @igorgladkoborodov 

> That’s an interesting feature request. What is your use case for this?
> [...]
> In my personal common workflow it will help opening files from terminal output, for example for failed tests.

My common use case is also project-oriented, same as you: for opening files because of failed tests, or because they were listed as a result of `grep` or `git status`, or whatever else might show a file name.

> I am going to do something similar. I want to add an option to open files by default in the existing VV instance if that file is in the already opened project

That's a very nice idea! 

In fact, If there are multiple VV instances already open (working on multiple projects) it would be nice if VV were to choose the appropriate instance for the file being opened. That'd be better than gvim `--remote` which chooses the most recent instance which isn't necessarily right.

> ...already opened project (i.e. the file to open is in subdirectory of `:pwd` of existing VV instance).

Basing on `:pwd` assumes that you run VV the first time at the project root.  That's a reasonable assumption but I'm not sure it's always true in my use case.  Still, I could probably train myself to run VV at the project root.

Another difficulty with using `:pwd` is that I use `autochdir` -- a typical project has a whole directory tree full of files, and so at any given moment `:pwd` is at some subtree of my project.   To work around that, maybe VV could remember the starting `cwd` separately from the `:pwd` setting?  Or else I could replace `autochdir` with `auto BufEnter * silent! lcd %:p:h` to avoid changing the global `:pwd`

It would be nice though if VV could somehow determine the project root some other way.  I was starting to imagine some configurable settings/options for VV to search for `.git` or other things...   but then I thought it would be neat if (Neo)vim would itself know what the project root is and then VV could query it.

So here's a thought:  What if VV were to check if there's a `project_root` variable defined?  If so VV would use it.  Then my `.vimrc` or a suitable plugin could decide what the root is.    Bonus could be if VV were to check that separately for each buffer, resulting possibly in a list of project roots -- and the VV instance would be used if the file to be opened were under *any* of the listed roots.   `:pwd` could still be used as a baseline/fallback.

> There is also a big question how exactly to open the file: in the existing window, in a new tab or split. Maybe it could be controlled by cli options similar to gvim's `--remote` or respect `switchbuf` setting or add specific VV settings or cli options. 

Yeah that's a good question.  `gvim --remote`'s default behavior is to move the cursor to an existing buffer window if the file is already open, or replace an existing buffer window with the new file or split to create a new buffer window based on whether the current buffer has unsaved edits.  That's OK, but I think I'd be happier with something consistent, such as always splitting if the file isn't already open.   Though ultimately I don't think I care too much -- as long as the file is in an open buffer window I can manage the rest easily enough :)

> I don’t want to use `--remote*` CLI options from gvim to avoid confusion, because most likely it will have different functionality.

Yeah I agree better to use different option(s).

BTW It would be nice I think to have options to override the behavior in both directions: an option to force opening a file in an existing instance even if it's not in the same project (sometimes I'm working on two different projects at once); and an option to force opening in a new instance even if the file's in the same project (sometimes I've got a bunch of related files in a buffer list, and I want to briefly open a different file in the project without tainting that list).

In any case, thanks for thinking about this -- whatever solution you come up with I'm likely to be able to adapt to!  And thanks for making VV -- I've been wanting "A pure, fast, minimalistic Vim experience with good macOS integration" since I first heard about Neovim, and none of the existing GUIs I've found have fit the bill.

**Comment by igorgladkoborodov** [comment]
Great, thank you for your feedback. I want to take some time to think and come up with some demo hopefully next week.

**Comment by igorgladkoborodov** [comment]
Hey @ronen, sorry for late response. I came up with this #42:

> If you already opened VV and it has `:pwd` `~/apps/vv`, and you call `vv src/main/index.ts`, it will open this file in the existing instance.
> * You can turn it on or off by `:VVset openInProject=1` or `:VVset openInProject=0`. It is on by default.
> * By default it will respect [`switchbuf`](https://neovim.io/doc/user/options.html#'switchbuf') setting. It will work the same as files opened from [quickfix](https://neovim.io/doc/user/quickfix.html) list. In fact it uses a temporary quickfix list to open files to absolutely mimic it's behavior.
> * You can set custom options to override `switchbuf` setting by `:VVset openInProject=[switcbuf override]`, for example, `VVset openInProject=newtab`.
> * Additionally you can override both of these using command line argument `--open-in-project`. For example: `vv --open-in-project false [filename]` to open in new VV instance, `vv --open-in-project newtab [filename]` to open file in new tab.
> * When you open the file, it compares file name with nvim current directory (result of `:pwd`), so if you initially opened file from somewhere else, you can use plugins [vim-rooter](https://github.com/airblade/vim-rooter) or [vim-findroot](https://github.com/mattn/vim-findroot) or similar.

What do you think about this interface? I am going to merge it in a couple of days, want to test it more, add docs etc. I am using it for a while now, it is quite useful, for example when you Cmd+Click file name in iTerm on failed tests.

**Comment by ronen** [comment]
Hey @igorgladkoborodov thanks for getting back to me on this.  I tried a local build of the `open-existing` branch and it worked as advertised -- cool!

But unfortunately it doesn't quite work for my use case, because I use [autochdir](https://neovim.io/doc/user/options.html#autochdir) -- rather than keeping `pwd` at the project root, the `pwd` for each buffer is the local directory of the file in that buffer.

So, if, e.g. If I open a file using `vv src/main/index.ts` then vv changes to the local directory so that it now has `:pwd ~/apps/vv/src/main`; so If I open another file in the project such as `vv src/lib/log.ts` it's not under the current `pwd` and opens in a new window. 😞 

One simple modification to your interface could be to check if there's a variable `projectRoot` (or whatever) in the current buffer, and if so use it, otherwise use pwd as you do now.  I.e., change https://github.com/vv-vim/vv/blob/a59a35d76afeaf8e20cd64e302828c064fd1a307/src/main/index.ts#L107-L116 to something like:

```js
      windows.map(async (win) => {
        const nvim = getNvimByWindow(win);
        if (!nvim) {
          return Promise.resolve();
        }
        const projectRoot = (await nvim.getValueOfVar('projectRoot')) || (await nvim.callFunction('getcwd', []))
        // @ts-ignore TODO: don't add custom props to win
        win.cwd = projectRoot; // enlist-disable-line
      }),
    );
```

It would then be up to me to set `projectRoot` for each buffer if I wanted to.  I would try it myself except that I don't know enough about nvim to know to write `nvim.getValueOfVar`() 🙃

**Comment by igorgladkoborodov** [comment]
Hey @ronen, thank you for feedback. I added a [`VVprojectRoot`](https://github.com/vv-vim/vv/pull/42/files#diff-bbd9aa632f9c087948e754dbf6f9adc0R38-R40) function and call it in `main/index.ts` instead of `getcwd`, so now you can override like this:
```vim
function! VVprojectRoot()
  return g:projectRoot " Or anything else
endfunction
```

I think that it will be more flexible. What do you think? Will that work for your workflow?

**Comment by ronen** [comment]
Hey @igorgladkoborodov, sorry for the long delay...

> I think that it will be more flexible. What do you think? Will that work for your workflow?

I tried out this:

```vim
function! VVprojectRoot()
    let gitroot=system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
    if !empty(gitroot) | return gitroot | endif
    return getcwd()
endfunction
```

And it seems to be working fine.   I haven't yet had a chance to really work with it in my workflow but I expect/hope it'll be fine.

Thanks!
