### ISSUE TITLE
Support run vv in the browser

### ISSUE THREAD

**Issue by smartrejames** [vv-vim/vv#47]
Like code-server for VS Code, is it possible to make vv run in the browse?

**Comment by igorgladkoborodov** [comment]
Hi. It is currently not designed to run in browser with remote server. But technically it is possible to rewrite client part to work with remote nvim instance or something like that. What is your use case?

**Comment by smartrejames** [comment]
Hi hi @igorgladkoborodov , just want an alternative lite toy to code-server to code on any machine anywhere :D

**Comment by igorgladkoborodov** [comment]
@smartrejames Made a working demo, this is kinda fun to see it work in browser. But there is a lot of work here. Added milestone with a bunch of initial issues to manage this https://github.com/vv-vim/vv/milestone/1
Closing this one.
