### ISSUE TITLE
Open files in buffers instead of windows

### ISSUE THREAD

**Issue by whitelynx** [vv-vim/vv#8]
From `README.md`:
> You can specify one or more space separated files or directories. They will be opened in separate windows.

I'd like one `vv` invocation to open one window, and to just open the listed files in buffers in that one window. Is there an option that would allow me to do this?

**Comment by igorgladkoborodov** [comment]
This is not currently possible. I am going to review the startup options, will consider this.

**Comment by igorgladkoborodov** [comment]
@whitelynx Changed cli to pass options to `nvim` without changes. So now when you run `vv` with the list of files it will open them as buffers in the same window.
