### ISSUE TITLE
VVset for multi worded fonts create an error

### ISSUE THREAD

**Issue by StevenJPx2** [vv-vim/vv#92]
This is a visual issue that I'm facing with.

Here's a side-by-side comparison between VV and Alacritty's terminal nvim:

### VV
![VV](https://i.imgur.com/EIVwbau.png)
### Terminal nvim
![Alacritty](https://i.imgur.com/rkJOVfN.png)

### VV
![VV](https://i.imgur.com/l6YSylC.png)
### Terminal nvim
![Alacritty](https://i.imgur.com/iyGwMzM.png)

Let me know if you want any more details from me.

**Comment by StevenJPx2** [comment]
Main issue with this is because I cannot set the nerd font using `VVset` like I did with `alacritty.yml`.

```vim
if exists('g:vv')
  VVset fontfamily="Hack Nerd Font Mono, monospace"
  VVset fontsize=12
endif
```

This gives the error:
![Error](https://i.imgur.com/Fm16x1e.png)

**Comment by igorgladkoborodov** [comment]
Hi @StevenJPx2. Can you try to use PostScript name of font? You can find it in Font Book app in font information. For example:
<img width="999" alt="Screen Shot 2021-04-01 at 12 38 01 PM" src="https://user-images.githubusercontent.com/9132/113345459-54a2fb00-92e7-11eb-9ba3-c49af01b707d.png">

If this will not work, could you please attach the font you are using? I will try to reproduce it locally.

**Comment by StevenJPx2** [comment]
It worked! The dev fonts now load in properly, but the pipes still don't connect. It would be good to mention that font-family would work with the Postscript name.

**Comment by igorgladkoborodov** [comment]
I checked this font issue. Regular font name with spaces works, but you need to escape spaces with `\`, no quotes needed. Updated readme to reflect that. So `:VVset fontfamily=Hack\ Nerd\ Font\ Mono,\ monospace` will work. Also now it will always add `monospace` to the font list, so it will be readable even if fonts are not installed. 

Also you can use standard [`guifont`](https://neovim.io/doc/user/options.html#'guifont') setting with `hXX` option (other options are not supported yet). `set guifont=Hack_Nerd_Font_Mono:h11` is the equivalent of `VVset fontfamily=Hack\ Nerd\ Font\ Mono` and `VVset fontsize=11`. So you don't need special font config for VV and you can share the same font config with other clients.
