### ISSUE TITLE
cursor hop in terminal buffers

### ISSUE THREAD

**Issue by ratmav** [vv-vim/vv#94]
hi! thanks for making vv, and i'm looking forward to using it! after building on the head of master today (latest macos, npm, and yarn), i started using vv to edit my dotfiles, and i'm a heavy user of the embedded neovim terminal. while in insert mode inside a window with a terminal buffer, the cursor hops around, which can make it tricky to follow what i'm typing. i've attached a video that hopefully shows what i'm talking about:

https://user-images.githubusercontent.com/1655830/113525517-67d1f700-9583-11eb-9cb9-055e7bf0d032.mov

i was using hyper.js prior to vv, which doesn't seem to have this issue. any ideas on where i could start looking around if i wanted to try and fix this myself?

**Comment by igorgladkoborodov** [comment]
Hi, sorry for late reply. I will take a look at it today. Need to see what exactly nvim is sending to redraw in this case (for example, you can console.log `cmd` and `props` here https://github.com/vv-vim/vv/blob/main/packages/browser-renderer/src/screen.ts#L765).
Maybe this is related to #68, I did not merge that PR because it seems kinda hacky for me, but maybe I will still need to do that workaround.
Anyway, I will check it later today.

**Comment by igorgladkoborodov** [comment]
Hey @ratmav can you try to build it from `fix-terminal-cursor` branch? Does it fix your problem?

**Comment by ratmav** [comment]
the workaround i see in the diff is totally usable; just a slight flicker. looking at pr 95 for the fix-terminal-cursor branch,  i see a lot of type setup and then what i think is ultimately a redraw [here](https://github.com/vv-vim/vv/pull/95/files#r611243731). 

i was also looking at uivonim, which has the same issue, logged [here](https://github.com/smolck/uivonim/issues/14).  i'm not familiar yet with what is meant by "cursor-movement" and "drawing-pen-movement", however i'm willing to dive in and figure it out. mentioning this in case you're already familiar and the information is clarifying enough for you to visualize a more complete solution faster than i would figure one out.

also, my daily driver right now is [hyper](https://github.com/vercel/hyper), which doesn't seem to have this issue at all. that said, it's a full blown terminal emulator, which feels silly for my use case b/c i use the terminal emulator provided by neovim's libvterm.

finally, i'd like to say thanks for publishing this application. it's the cleanest/simplest "just a neovim client" (no eye candy, keep the config in init.vim, just use vim plugins and skip vscode extensions, etc.) i've found. i also appreciate that you responded to my issue at all; no need to apologize for a late reply: i hope you enjoyed your weekend.

**Comment by igorgladkoborodov** [comment]
Thank you!
Will try to fix flickering, maybe throttle cursor redraw or something. Will need to investigate it.
